name: CI workflows
on: [push, pull_request]

jobs:
    build:
        name: Check TypeScript
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: oven-sh/setup-bun@v1

            - name: Install dependencies
              run: bun install

            - name: Run TypeScript Compiler
              run: bun run typecheck