name: CI workflows
on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repo
              uses: actions/checkout@v2

            - name: Set up Node v16
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  cache: "yarn"

            - name: Install dependencies
              run: yarn install

            - name: Run linter
              run: yarn lint

    typescript:
        name: TypeScript Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Node v14
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  cache: "yarn"

            - name: Install dependencies
              run: yarn install

            - name: Run TypeScript Compiler
              run: yarn build

    tests:
        name: Mocha tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Node v14
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  cache: "yarn"

            - name: Install dependencies
              run: yarn install

            - name: Run TypeScript Compiler
              run: yarn build

            - name: Run tests
              run: yarn test
